version: '3.3'

services:

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE:-app}
    environment:
      - EMAIL_DISABLED=false
    ports:
      - "8080:8080"
